### ISSUE TITLE
Qualifications

### ISSUE THREAD

**Issue by anguslockhart** [carlson9/SentimentIt#1]
Is it possible to access the MTurk qualifications through this package?  In particular I am hoping to get work done by workers in Germany.  I know I can add an external qualification to test their german but I would rather just use the built in German feature.

Thanks,

Angus Lockhart
Simon Fraser University

**Comment by carlson9** [comment]
At this point, MTurk does not support premium qualifications via API:

[https://forums.aws.amazon.com/thread.jspa?messageID=760343](https://forums.aws.amazon.com/thread.jspa?messageID=760343)

Hopefully we will be able to in the future, but at this point speaking German is not a supported qualification. However, note the last statement on the thread, that your own test will not charge you additional money, so in the long-run writing your own test may make the most sense so you do not have to pay the up-charge for premium qualifications.

If you still want to use MTurk's premium qualification, you can use this package for some of its functionality, including analyzing the results and the workers, but it will not be as stream-lined.

Let me know if you have any other questions,
Dave Carlson

**Comment by anguslockhart** [comment]
Oh I'm not talking about the premium qualification.  I was hoping to use the location qualifier that I've managed to use when I access the API directly.

**Comment by carlson9** [comment]
I have not tried it, but I believe all you would need is the qualification ID in that case which you can query. On the SentimentIt system you would simply use this ID when setting up a new qualification on our system to link it to the AMT system. Again, though, we have not tried this.

**Comment by anguslockhart** [comment]
It appears that I would need to enter all of 

"<QualificationRequirement>
  <QualificationTypeId>00000000000000000071</QualificationTypeId>
  <Comparator>EqualTo</Comparator>
  <LocaleValue>
  <Country>DE</Country>
  </LocaleValue>
  </QualificationRequirement>"

But I've got no clue how I might get from what to an amazon ID.  Sorry if this is a silly question, I am very new to work with APIs!
